# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

FROM python:3.7.9-alpine3.12

COPY server.py .
COPY req.txt .
RUN pip install --upgrade pip
RUN pip install cmake
RUN pip install -r req.txt
CMD ["/usr/local/bin/python3", "server.py", "5005"]